### PR TITLE
Added getters to Slacker for members

### PR DESCRIPTION
**Pull request by ayjayt**
Last one, I promise! Very simple.

**Purpose:**

Exposing _nlopes/slack_ members in the `slacker` structure allows us to create an arbitrary slack bot, and then use "slacker" as a command/control interface for it. E.g.: A slack bot that relays important logs in RTM w/o command, but can be fine-tuned by slacker commands.

**Implementation:**
Created Getter func's for said purpose

### CODE REVIEW

**Comment by shomali11** [comment]
Don't apologize! I love seeing your PR and I am very appreciative of all your hard work.

Regarding exposing the Client and RTM, they are already available as part of the Response object.

Here is an example:
https://github.com/shomali11/slacker/blob/master/examples/example7.go#L19

**Comment by ayjayt** [comment]
This way is actually very nice for me because it allows me to use Slacker as a general purpose slack package- I can use RTM and Client before a command has been called, and then users can also use commands to adjust the bots default behavior.

I will be demoing it in a go logger implementation for slack in the next few days, time willing.

**Comment by shomali11** [comment]
I do not have a problem with this, and I can merge it.

I am just curious, what kind of things were you planning on using RTM and Client before a command has been called?

**Comment by ayjayt** [comment]
Two use cases:

1) Gathering information about the bot user on initialization
2) Restoring settings saved after a reset

**Pull request merged**
