### PR TITLE
Sanitize input for copypasted cmds

### PR DESCRIPTION
**Pull request by themarcelor**
When someone copies & pastes commands, they end up with a weird character `\u00a0` so the command ends up being ignored.

> U+00A0 No-Break Space (NBSP) Unicode Character).

e.g., The payload shows something like "text":"\u00a0my-command arg1 arg2"

The payload can be visualized if we start Slacker in DEBUG mode:
```
                bot = slacker.NewClient(slackBotToken, slackAppToken, slacker.WithDebug(true))
```

This PR attempts to sanitize the input.

### CODE REVIEW

**Comment by arusso** [comment]
This should be a function (like the original `SanitizeText()`) that has a reasonable default in Slacker but that can be overridden by a user.

Trimming the string of whitespace (including nbsp) seems like a reasonable default to me.

**Comment by themarcelor** [comment]
Thanks for the reply @arusso , so is this private function suitable?

**Comment by arusso** [comment]
The method itself is fine, but it needs to be overridable by a consumer of
slacker.

Initially I was thinking this would be a Slacker struct func that can be
overridden by a WithClientText ClientOption, but that requires the
ClientDefaults to contain the method as well which I’m not sure is a good
idea.

I’ll sit down and look at this later today and propose how to move it
forward.

**Comment by arusso** [comment]
Hmm. I wish we could do something about the ClientOptions versus Slacker pointer receivers for providing options / overrides. In this case I think its more appropriate to use a pointer receiver method on the Slacker struct:

So add our function to the Slacker struct:

```
struct Slacker {
 ...
 cleanEventInput func(in string) string
 ...
}
```

Then rename what you have to indicate it's the default and set it in the `NewClient()` function:

```
func defaultCleanEventInput(in string) string {
  ...
}

func NewClient() {
  ...
  slacker := &Slacker{
    ...
    cleanEventInput = defaultCleanEventInput,
    ...
  }
}
```

Finally add a method w/pointer receiver for *Slacker to set the cleanEventInput so it can be overridden:

```
func (s *Slacker) CleanEventInput(cei func(in string) string) {
  s.cleanEventInput = cei
}
```

Then where you are calling `cleanInput` now you would call `s.cleanEventInput`, which will call whatever function 
`Slacker.cleanEventInput` is set to.

A user can then override this to be whatever they want with some initialization code like:

```
slacker = NewClient(...)
slacker.CleanEventInput(func (in string) string {
  // noop, just return what we got.
  return in
})
```

**Comment by themarcelor** [comment]
I get what you're saying 🤔 ... I've pushed another commit but it's not 100% yet.
I need to figure out how to define a default input-cleaning function in `defaults.go` .

But what do you think about this approach so far?

**Comment by themarcelor** [comment]
Actually. Let me take a look at your latest reply...

**Comment by themarcelor** [comment]
Btw, the latest commit was successfully tested in my Slack channel 💪🏼 
I wonder if we could still refactor that code a bit... 
maybe I should rename `defaultCleanEventInput ` to `defaultCleanEventInputFunc` and move the script into `defaults.go`? what do you think?

**Comment by arusso** [comment]
I wouldn't make any of those changes -- not because they're bad ideas (they aren't) but because it doesn't really correspond to the original style of the Slacker code base. For example, `Slacker.Err(...)` overrides the default error handler in `slacker.go` and has neither of those properties.

What should be changed --

It looks like the last commit overwrote the `CleanEventInput()` override function so that still needs fixing.

Run `go fmt` as I see some obvious formatting issues.

Also, once you're done please squash this all down into a single commit w/a concise commit message.

**Comment by themarcelor** [comment]
alright @arusso , I guess that should be ok now (right?).
Thanks again for the guidance.

**Comment by arusso** [comment]
Looks great!

Can you run `staticcheck` over the repo and clear up any issues it brings up with the new code? I see one which is the comment format for `CleanEventInput`.

Can you also add a trivial example to the README and examples dir?

Otherwise things look good and I'll do a final review / merge later this evening.

**Comment by themarcelor** [comment]
Done @arusso 💯 

My staticcheck run did not capture any issues with that code comment though.
looks like it's all good:
```
slacker [sanitize_input_for_copypasted_cmds] % staticcheck ./...
slacker [sanitize_input_for_copypasted_cmds] % echo $?
0
```

**Comment by arusso** [comment]
Ah, looks like my `staticcheck.conf` enables more checks than the default. I'll include one in the base of the repo to include more than the default checks. Here's the one I was referring to:

```
> staticcheck ./...
slacker.go:111:1: comment on exported method CleanEventInput should be of the form "CleanEventInput ..." (ST1020)

> staticcheck -explain ST1020
The documentation of an exported function should start with the function's name

Doc comments work best as complete sentences, which
allow a wide variety of automated presentations. The first sentence
should be a one-sentence summary that starts with the name being
declared.

If every doc comment begins with the name of the item it describes,
you can use the doc subcommand of the go tool and run the output
through grep.

See https://golang.org/doc/effective_go.html#commentary for more
information on how to write good documentation.

Available since
    2020.1, non-default

Online documentation
    https://staticcheck.io/docs/checks#ST1020
```

Go ahead and squash things back down into a single commit and then I'll merge this in.

**Comment by themarcelor** [comment]
hi @arusso , just checking: Any additional thoughts on these changes?

**Comment by arusso** [comment]
Nope! Just been busy and haven’t been able to merge. I’ll try and get to it
this evening.

**Pull request merged**
