### PR TITLE
adding an unhandled event mechanism

### PR DESCRIPTION
**Pull request by lusis**
This adds a function where any unhandled events can be published. A good use case for this is things like "my bot joined a channel and I need to do X"

The upshot is also that you don't need to expose everything individually in this library if it doesn't make sense or as the api changes.

### CODE REVIEW

**Comment by lusis** [comment]
It's worth noting that if anyone needs to assert/switch on the unhandled event types, they'll need to ensure that when they vendor this library they don't include its vendored deps.

**Comment by shomali11** [comment]
I really like the idea. The only concern I have is the naming.

Currently, there is a `defaultHandler` that handles messages that do not match any commands.
And now we will have an `unhandledHandler` that handles events that slacker is not handling.

What do you think about renaming:
`defaultHandler` -> `defaultMessageHandler`
`unhandledHandler` -> `defaultEventHandler`

Do you think those would be a little more readable and intuitive?

**Comment by shomali11** [comment]
Definitely but I would prefer to have the renames suggested implemented first to avoid confusion.

**Comment by shomali11** [comment]
Since the PR has not been updated for a while, I already made the changes and committed them.

I am closing this one.

**Pull request closed without merging**
