### PR TITLE
Allow custom bot command constructor

### LINKED ISSUE #97: Allow overriding command constructor
Add the option for the user to provide a custom command constructor.
This can be used to prefix all commands with the bot name to make the bot respond to messages without proper Slack mention (for example instead of `@MyBot ping` you can make it listen to all messages in the channel, add the name prefix to the command and invoke `mybot ping`)
In out use case we need it to pass customize the creation of the commander command (See https://github.com/shomali11/commander/pull/3).

### PR DESCRIPTION
**Pull request by asafalima**
Resolves #97

### CODE REVIEW

**Comment by asafalima** [comment]
@arusso Can you please review this PR?

**Comment by arusso** [comment]
Hi @asafalima --

It's not clear to me how this might be used -- can you help me understand what value this brings?

As for the contribution in it's current state before it were to be merged I'd like to see --
- An example provided in the README and a copy of it in the examples/ directory
- Run the changes through `staticcheck` and resolve any raised issues

I encourage you to review our [Contribution Guidelines](https://github.com/shomali11/slacker/blob/master/CONTRIBUTING.md). Clearly understood issues w/accompanying pull requests are more likely to be reviewed than a pull request without any other information.

And finally, thanks for your willingness to contribute back to Slacker!

**Comment by asafalima** [comment]
Hi @arusso,

An example was added and I've created an issue.
Also staticcheck passed

**Comment by shomali11** [comment]
I am not sure what the real purpose of this PR and the one in the `commander` repo are for.

If the intention is to provide your own Command Parsing logic, then the better approach is to allow for a way for one to provide their own "commander" instead of the one I wrote.

Perhaps some clean up may be required to make it more generic and easily "swappable"

**Comment by arusso** [comment]
@shomali11 are you thinking a `CommandParser` interface? It's something I've considered before and I oscillate between loving the idea and wanting a more flexible parser versus wanting to be careful not to make the UX different for each developer that creates their own parser. Suddenly "usage" strings would be different, though that may not be that big of a deal. I think it's worth exploring, though maybe not in this PR.

That said, I don't have any major concerns with this PR and I could probably think of a few cases were it would be useful even with the generalization of the command parsing. I would like to see `CustomCommand(...)` changed to `CustomCommandConstructor(...)`, however.

Though if I'm understanding the underlying problem they're trying to solve, I wonder if it wouldn't be simplest to just have a bot-level prefix that gets added to each command and add that logic to NewBotCommand().

**Comment by arusso** [comment]
Merged in #104

**Pull request closed without merging**
