### PR TITLE
Add support for slash commands

### PR DESCRIPTION
**Pull request by ctennis**
Add support for setting a slash command handler, much like the interactive event handler.  I don't Ack the event (it's commented out) as the reference handler doesn't ack the event as well, but we can uncomment it if it makes sense to Ack the event here.

### CODE REVIEW

**Comment by shomali11** [comment]
@arusso It looks fine to me. Should we acknowledge the event?

Do you have any feedback on how to improve this?

**Comment by josephlim75** [comment]
any progress of when we can merge the slash command enhancement to the code ?

**Comment by arusso** [comment]
I'm still waiting for the following changes before merging:

- A slash command should be similar to CommandDefinition in how they are defined and managed.
- We should ack events as they come in with socketmode.Ack.

**Comment by arusso** [comment]
Closing this in favor of the implementation in #100 that was merged in.

**Pull request closed without merging**
