### PR TITLE
Use SocketMode for connections

### LINKED ISSUE #63: This only works with "classic" slack apps
I think the README should be updated to indicate it uses the RTM API which does not function with new slack apps that have granular oauth permissions.

Took me 40 minutes to figure out what was going on by finally dropping the debug option in the config and seeing:

```
slack-go/slack2020/07/18 13:56:31 websocket_managed_conn.go:177: Connecting to RTM
slack-go/slack2020/07/18 13:56:32 rtm.go:71: Using URL:
slack-go/slack2020/07/18 13:56:32 websocket_managed_conn.go:181: Failed to start or connect to RTM: not_allowed_token_type
slack-go/slack2020/07/18 13:56:32 websocket_managed_conn.go:147: reconnection 1 failed: not_allowed_token_type reconnecting in 100ms
...
```

It is possible to still create apps that use the old permissions scopes but they are pushing everything to the events API.

More info in this thread https://github.com/slackapi/node-slack-sdk/issues/921#issuecomment-644317329

### PR DESCRIPTION
**Pull request by arusso**
Updates Slacker to use the Events API over the SocketMode communication protocol, replacing calls to the deprecated RTM API.

A few key functions have changed, notably the NewClient function now requires both an App and Bot token to be specified. In addition, the typing indicator is not supported in SocketMode and has been removed altogether.

Fixes #63

### CODE REVIEW

**Comment by shomali11** [comment]
This is incredible work! Thank you very much!

I have a couple of questions:
What was the reason for dropping the `Typing` indicator?
Is this functionality not supported via the `SocketMode` Client? 
Can we not recreate it via the `slack.Client` API?

It seems there are now two Clients. The `slack.Client` & `socketmode.Client`. 
Do we need both? Can the `socketmode` version do everything that the `slack` one does? 
If not, perhaps we should drop the former. 
If yes, perhaps we should rename them so that the user is not confused. 
Maybe We expose the `slack.Client` as `API` while `socketmode.Client` as `Client` everywhere (specifically `BotContext`).

Fantastic work. Thank you again for all of this!

**Comment by arusso** [comment]
The Typing indicator is exclusive to the [RTM API](https://api.slack.com/events). Here's an [issue](https://github.com/slackapi/node-slack-sdk/issues/1130) where a Slack dev chimes in on the thinking behind that decision.

The `slack.Client` is needed to interact with the Slack API, the `socketmode.Client` doesn't export it's `apiClient`  unfortunately. The `socketmode.Client` handles sending/receiving those events. Practically speaking, `socketmode.Client` takes the place of RTM in slacker thanks to the slack-go maintainers [ensuring it behaved in a similar fashion](https://github.com/slack-go/slack/blob/master/socketmode/client.go#L39) which made it fairly straightforward to swap in.

The event processing happens entirely within slacker though, and without interactive methods like `RTM.Typing()` exposed via the `socketmode.Client`, it's utility may be limited to [setting up debug logging / connection parameters](https://github.com/slack-go/slack/blob/master/socketmode/socketmode.go). Personally I think that's worth inclusion in the `BotContext`.

Regarding naming, I kept `Client` named as such to minimize the amount of changes being made and that would be required by developers. For example my bots make heavy use of the slack.Client as exposed by ctx.Client() and renaming that to something else and making the socketmode.Client `Client()` would be a little confusing (and more importantly confuse developers less familiar with the inner workings).

Personally, I think it's better to keep that named the same so as as to avoid this situation. I don't have a strong opinion on the `SocketMode` name if it's kept, I was again trying to maintain consistency with the RTM implementation by naming it after the component.

On a related note, I don't know how you feel about module versioning but it does seem like this would be a good place to cut a new version. That way devs can expect they'll need to do some level of modification of their code in order to update to the new version and there's a clear cut between RTM and SocketMode versions. That's probably outside this specific PR, but I felt it worth mentioning. I'm also working on adding support for `SlashCommands` which may or may not factor into this discussion at all.

At any rate, let me know how you feel about the naming / client exposure and I'll update things accordingly.

**Comment by shomali11** [comment]
You are very convincing. I agree with you on pretty much everything.

One question, is the SocketMode supposed to completely replace RTM? Is RTM going to be deprecated? If not, would it ever make sense to give the user the option whether they want to connect with RTM or SocketMode?

My assumption is that the tokens users currently have would not work with the SocketMode. Correct? I wonder if there is a way to detect that and return an error to educate the user.

I believe you are absolutely correct that we have definitely gotten to the point where a new version is needed. Would you be open to creating another PR for it?

I am looking forward to the `SlashCommands`

**Review by shomali11 — APPROVED** [review]
🎉

**Comment by arusso** [comment]
> One question, is the SocketMode supposed to completely replace RTM? Is RTM going to be deprecated? If not, would it ever make sense to give the user the option whether they want to connect with RTM or SocketMode?

RTM is only supported with "Classic" or "Legacy" apps which I believe are officially deprecated with no new features being introduced, and eventually to be retired. The Classic/Legacy Apps are increasingly difficult to create these days (they hide it in the interface). Socket Mode seems to be their answer to RTM, which was kept around for a while since it was the only way to connect from behind the firewall.

> My assumption is that the tokens users currently have would not work with the SocketMode. Correct? I wonder if there is a way to detect that and return an error to educate the user.

I think a user can upgrade their legacy app to a "modern?" app within Slack. I'm not sure if the bot token remains the same or it if changes. They'll get a new app token that they'll need to pass to the new client initializer, so I'm not sure if it makes sense to try and detect this event.

> I believe you are absolutely correct that we have definitely gotten to the point where a new version is needed. Would you be open to creating another PR for it?

It seems like the correct way to do this is to put the code for the v2 version into a `v2/` directory. If SocketMode is the cutoff for v2, maybe I amend this PR? That'll also leave the original code around in case folks still want to use RTM.

**Comment by shomali11** [comment]
Alright. I agree with your points.

> It seems like the correct way to do this is to put the code for the v2 version into a v2/ directory. If SocketMode is the cutoff for v2, maybe I amend this PR? That'll also leave the original code around in case folks still want to use RTM.

Technically speaking, this project has been in `v0` this entire time. Do we need to jump to `v2`?
I believe all we need is a git tag of `v1.0.0`.

I wish versions in Go (v2 and above) didn't require directories and changing module names.

With the v1 version we can continue to maintain the `go get github.com/shomali11/slacker` call and you would not need to modify your PR to support both the old and new ways.

But if `v2` is the way, I am fine with that too.

What do you think?

**Comment by arusso** [comment]
> Technically speaking, this project has been in v0 this entire time. Do we need to jump to v2?
I believe all we need is a git tag of v1.0.0.

That's true. Just tagging `v1.0.0` is probably the better way to go here.

**Comment by arusso** [comment]
Thinking about this some more -- maybe we hold off on tagging a v1.0.0 until we're comfortable with the interface not changing. Although the move from RTM -> SocketMode/Events API required minimal change, I'd hate to cut a a release only to find the interface doesn't work well when looking to implement SlashCommands, and then have to re-increment so soon (to follow module versioning best practices).

The addition of Slash commands should tease out whether any interface changes are needed since that's not part of the Events API.

**Comment by arusso** [comment]
I added a `SocketMode()` on the Slacker struct akin to the `Client()` method so that you can access the `socketmode.Client` during setup and not just within commands via `BotContext`.

**Review by shomali11 — APPROVED** [review]
👍

**Comment by shomali11** [comment]
It might be nice to add something under the "Features" list in the README.md about SocketMode.

I approved it, you can merge it whenever you are ready.

**Comment by arusso** [comment]
Alright, I think I'm done. I added Socket Mode support to the features list and bumped the dependency of slack-go to v0.9.1 (current version). If you're good with the go.mod changes then I think we're ready to merge!

**Comment by shomali11** [comment]
Looks great! Thank you again very much for the spectacular work! Your PRs are always welcome!

**Pull request merged**
