### PR TITLE
Allow event handler to be configured

### PR DESCRIPTION
**Pull request by smoya**
Example of usage:

```go

handler := func(ctx context.Context, s *slacker.Slacker, msg slack.RTMEvent) error {
	switch event := msg.Data.(type) {
		case *slack.MessageEvent:
			// do any special process, like filter messages by channel and process them.
	}
	return slacker.DefaultEventHandler(ctx,  s, msg)
}
bot := slacker..NewClient(token, slacker.WithEventHandler(handler))
```

### CODE REVIEW

**Comment by shomali11** [comment]
I am curious to learn about your use case and why you would need to overwrite the entire event handler to do this.

The point of encapsulating this is to hide the complexity and all the different cases that the user needs to consider and worry about. Perhaps if you share what you want to accomplish, we can figure a way to improve the current event handler to accommodate for your case.

**Comment by smoya** [comment]
I want to let my bot react to any message not only commands. I.e., a message was sent to channel #b and the bot wants to know in order to analyse such message.

**Comment by shomali11** [comment]
In that case, how would you feel about modifying the code as follows:

```
if s.isBotMentioned(event) || s.isDirectMessage(event) {
    go s.handleBotMessage(ctx, event)
} else {
    go s.handleOtherMessage(ctx, event)
}
```

This way you rename the existing `handleMessage` to `handleBotMessage` to indicate this is for bot related responses, and introduce a `handleOtherMessage` to handle all other SlackMessage events which then you could use to handle your case.

I like how you renamed the one in the default case to `fallbackEventHandler`, perhaps rename the method that sets it to `FallbackEventHandler`

Would this work or do you need to have complete control over everything in that block? If so, I would suggest naming that method `EventListener` rather than `EventHandler`

**Comment by smoya** [comment]
I guess that as far as we can have access to the raw Slack event, is fine!

**Comment by shomali11** [comment]
Awesome. Make the changes and I will merge your PR

Thank you very much!

**Comment by shomali11** [comment]
Any updates on this?

**Comment by mmcdole** [comment]
Just wanted to say I started to dig into the library to find a way to get access to the raw Slack Event as well.

Same use-case, I need to be able to respond to both commands and arbitrary messages.  I actually think @smoya's solution was preferable because it is the most flexible.

You can handle **any** event and gives you access to the raw event.  Your proposed solution @shomali11 only exposes the `Message` event.

**Comment by shomali11** [comment]
@mmcdole If that is the desired behavior, I guess I am fine with @smoya's solution. Let's hope he resolves the conflicting files and we can merge it.

**Comment by mmcdole** [comment]
@shomali11 I'll submit a new PR with his change + conflicts resolved.

**Comment by smoya** [comment]
A bit Late in my TZ but i will do tomorrow morning.

**Comment by smoya** [comment]
PR updated. I changed the way to override the handler by just implementing an option: `slacker.WithEventHandler(handler)`. I find this a better implementation as we don't need to expose the `EventHandler` var anymore.

**Comment by smoya** [comment]
@shomali11 ok to me if wanna merge

cc @mmcdole

**Comment by smoya** [comment]
@shomali11 With your solution, I'm concerned about acting to the same event twice

**Comment by shomali11** [comment]
@smoya @mmcdole You are right.

I have another idea. How about we extract this `switch` block into its own method that returns `bool` and `err` to indicate whether a message was handled (by the internal logic), if so, no need to pass the event to the fallback handler, otherwise we do.

For example:

```
func (s *Slacker) isEventHandled(msg slack.RTMEvent) (bool, error) {
			switch event := msg.Data.(type) {
			case *slack.ConnectedEvent:
				if s.initHandler == nil {
					continue
				}
				go s.initHandler()
				return true, nil

			case *slack.MessageEvent:
				if s.isFromBot(event) {
					return false, nil
				}

				if !s.isBotMentioned(event) && !s.isDirectMessage(event) {
					return false, nil
				}
				go s.handleMessage(ctx, event)
				return true, nil

			case *slack.RTMError:
				if s.errorHandler == nil {
					continue
				}
				go s.errorHandler(event.Error())
				return true, nil

			case *slack.InvalidAuthEvent:
				return true, errors.New(invalidToken)

			default:
				return false, nil
			}
}
```

This way, the `Listen` method would look like this:

```
// Listen receives events from Slack and each is handled as needed
func (s *Slacker) Listen(ctx context.Context) error {
	s.prependHelpHandle()
	go s.rtm.ManageConnection()
	for {
		select {
		case <-ctx.Done():
			s.rtm.Disconnect()
			return ctx.Err()
		case msg, ok := <-s.rtm.IncomingEvents:
			if !ok {
				return nil
			}

			handled, err := s.isEventHandled(msg)
			if err != nil {
				return err
			}

			if handled {
				continue
			}

			if s.fallbackEventHandler == nil {
				continue
			}
			go s.fallbackEventHandler(event)
		}
	}
```

I think this might work for everyone? What do you guys think?

**Comment by mmcdole** [comment]
Yea, it is good to be able to "consume" the event outside slacker, or for us to decide to pass the event along.

**Comment by mmcdole** [comment]
With the above solution, if the bot is mentioned in a message the custom fallback function will never be called because the bot is saying "this is my event".  The bot has consumed those message events.  This may make some sense for things like `AuthEvent` `RTMError` that I doubt people would want to handle themselves very often, but I basically never want it to be true for the `Message` event.

What if I want to do something on those message events myself and then also let Slacker handle them?  Or maybe conditionally decide if I want to pass the event along to Slacker to consume?

Maybe the idea of a "fallback" handler is the problem, this should be a `CustomEventHandler` that runs _first_, and if it returns false, _then_ Slacker will inspect the event.

```
// Listen receives events from Slack and each is handled as needed
func (s *Slacker) Listen(ctx context.Context) error {
	s.prependHelpHandle()
	go s.rtm.ManageConnection()
	for {
                event := msg.Data.(type)

                // Execute custom event handler if present.
                if (s.CustomEventHandler != nil) {
                    isHandled := s.CustomEventHandler(event)
                    if (isHandled) continue
                }

                switch  {
			case *slack.ConnectedEvent:
		// ...
```

Alternatively, you could just always call the CustomEventHandler after you handle it.  This has the drawback of both Slacker responding and some other process like your solution above, but at least I can get access to all events.

```
// Listen receives events from Slack and each is handled as needed
func (s *Slacker) Listen(ctx context.Context) error {
	s.prependHelpHandle()
	go s.rtm.ManageConnection()
	for {
                event := msg.Data.(type)

                switch  {
			case *slack.ConnectedEvent:
		        // ...
                }

                if (s.CustomEventHandler != nil) s.CustomEventHandler(event)
```

**Comment by smoya** [comment]
To be honest, I don't see a problem replacing the handler completely (as my first iteration did). You decide if wanna fallback or not inside the handler.

**Comment by shomali11** [comment]
I am still not convinced. Could you write a full example like the ones under the `example` folder?
I would like to see how you write a full example to handle specific raw messages with/without having to rewrite the message handling logic and command parsing.

**Comment by smoya** [comment]
Fyi, I have stopped using this library so unfortunately I'm not gonna give support to this PR anymorr.

I think efforts should be moved into using new Slack event subscriptions rather tha real time which is deprecated.

**Pull request closed without merging**
